# One RDS PostgreSQL 16 instance for the demo, holding one database per service, each owned by that service's own
# login role (services/*/db: every service still touches only its own database).
#
# Demo settings: single-AZ, no backups, no final snapshot, no deletion protection. Every demo-down deletes the
# instance and every demo-up starts empty; nothing here is meant to survive a demo.
#
# Passwords never enter the Terraform state:
#   master    RDS creates and keeps it in Secrets Manager itself (manage_master_user_password).
#   services  generated by an ephemeral resource (a fresh value on every run, never saved) and written to their
#             secrets through write-only arguments, which Terraform sends to AWS and then forgets. The *_wo_version
#             number says when to write again: unchanged, a later apply leaves the stored password alone.

resource "aws_db_subnet_group" "this" {
  name        = var.name
  description = "Private subnets for ${var.name}"
  subnet_ids  = var.subnet_ids
}

resource "aws_security_group" "this" {
  name        = "${var.name}-postgres"
  description = "Postgres: only from the given ECS tasks"
  vpc_id      = var.vpc_id

  tags = {
    Name = "${var.name}-postgres"
  }
}

# In: 5432 from each client's security group, nothing else. No egress rule: a database starts no connections.
resource "aws_vpc_security_group_ingress_rule" "from" {
  for_each = var.client_security_group_ids

  security_group_id            = aws_security_group.this.id
  referenced_security_group_id = each.value
  ip_protocol                  = "tcp"
  from_port                    = 5432
  to_port                      = 5432
  description                  = "From ${each.key}"
}

resource "aws_db_instance" "this" {
  identifier     = var.name
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage_gb
  storage_type      = "gp3"
  storage_encrypted = true

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.this.id]
  publicly_accessible    = false
  multi_az               = false

  username                    = var.master_username
  manage_master_user_password = true

  # Demo: a backup would only be restorable into the next demo, which starts empty on purpose. 0 also makes the
  # instance faster to create (no initial backup).
  backup_retention_period = 0
  # Demo: demo-down must delete the instance without leaving a snapshot behind (snapshots bill per GB-month).
  skip_final_snapshot      = true
  delete_automated_backups = true
  # Demo: protection would make every demo-down fail.
  deletion_protection = false

  # Changes happen now, not in the next maintenance window: the instance lives for an hour.
  apply_immediately          = true
  auto_minor_version_upgrade = true

  # Free 7-day Performance Insights would add nothing for an hour-long demo; Enhanced Monitoring costs extra.
  performance_insights_enabled = false
  monitoring_interval          = 0
}

# --- One login per service --------------------------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "app" {
  for_each = var.databases

  name        = "${var.name}/${each.key}-db-password"
  description = "Password of ${each.key}'s own database role"

  # Deleted at once on demo-down. The default 7-30 day recovery window would keep the name taken, and the next
  # demo-up would fail to create a secret with the same name.
  recovery_window_in_days = 0
}

ephemeral "aws_secretsmanager_random_password" "app" {
  for_each = var.databases

  password_length = 32
  # Letters and digits only: nothing that needs quoting in a JDBC setting, a shell or SQL.
  exclude_punctuation = true
}

resource "aws_secretsmanager_secret_version" "app" {
  for_each = var.databases

  secret_id                = aws_secretsmanager_secret.app[each.key].id
  secret_string_wo         = ephemeral.aws_secretsmanager_random_password.app[each.key].random_password
  secret_string_wo_version = 1
}
